daichi0913/freemarket_sample_59d

app/assets/stylesheets/login.scss
app/views/devise/sessions/new.html.haml
app/views/devise/sessions/origin_new.html.haml
config/initializers/recaptcha.rb

ログイン画面作成
facebookでログインボタンとgoogleでログインボタンが未完
ログイン機能は必須かなと

[WIP]user loginビューの作成

---

app/assets/stylesheets/_header_footer.scss
app/assets/stylesheets/sign_up.scss
app/views/devise/registrations/new.html.haml

[WIP]sign_up_view

---

app/assets/javascripts/users.coffee
app/assets/stylesheets/users.scss
app/controllers/users_controller.rb
app/helpers/users_helper.rb
app/views/users/show.html.haml
config/routes.rb
spec/controllers/users_controller_spec.rb
spec/helpers/users_helper_spec.rb

what
トップページの作成
why
トップページを作らないと始まらないから

toppageを編集

---

app/assets/stylesheets/_header_footer.scss
app/assets/stylesheets/sign_up.scss

sign_up_view

---

README.md

ER図の作成に伴い発見した問題点の修正。アソシエーションに関する記述の追加
データベース設計の情報を共有するため

[WIP]ER図の作成に伴うREADME.mdの変更

---

app/controllers/application_controller.rb
app/controllers/users_controller.rb
app/models/user_detail.rb
config/routes.rb
db/migrate/20190923015843_remove_columns_to_users.rb
db/migrate/20190923030032_add_image_to_users.rb
db/migrate/20190923031512_create_user_details.rb
db/schema.rb
spec/factories/user_details.rb
spec/models/user_detail_spec.rb

User controller make actions create

---

.gitignore
Gemfile
Gemfile.lock
app/views/devise/sessions/new.html.haml
config/initializers/recaptcha.rb

Login view4

---

app/assets/stylesheets/login.scss
app/views/devise/sessions/new.html.haml

Login view5

---

app/assets/stylesheets/_confirmation.scss
app/assets/stylesheets/_header_footer.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/sign_up.scss
app/views/devise/registrations/new.html.haml
app/views/devise/registrations/user_new.html.haml

[WIP]Confirmation09231130

---

app/assets/stylesheets/users.scss
app/views/users/show.html.haml

what 
ユーザーページの修正
why
ユーザーページが必要だから

userpageの修正

---

app/assets/stylesheets/application.scss

＃WHAT
"font-awesomesprockctsを消しました
＃WHY
"font-awesome-sassを消したから必要がないと考えました。

font-sprocketsを消した

---

app/models/brand.rb
app/models/brand_group.rb
app/models/item.rb
app/models/region.rb
db/migrate/20190925023954_create_regions.rb
db/migrate/20190925024306_create_brand_groups.rb
db/migrate/20190925024457_create_brands.rb
db/migrate/20190925024756_create_items.rb
db/schema.rb
spec/factories/brand_groups.rb
spec/factories/brands.rb
spec/factories/items.rb
spec/factories/regions.rb
spec/models/brand_group_spec.rb
spec/models/brand_spec.rb
spec/models/item_spec.rb
spec/models/region_spec.rb

＃WHAT
rails g model とrake:db migrate

brand, region, item brand_groupテーブルの作成

---

app/assets/javascripts/application.js
app/assets/javascripts/items.coffee
app/assets/javascripts/post_item.js
app/assets/stylesheets/items.scss
app/assets/stylesheets/post_item.scss
app/controllers/items_controller.rb
app/helpers/items_helper.rb
app/views/items/new.html.haml
config/routes.rb
db/seeds.rb
spec/controllers/items_controller_spec.rb
spec/helpers/items_helper_spec.rb
spec/views/items/new.html.haml_spec.rb

//= require jqueryの記述
jqueryを使えるようにするため

Post item view09251215

---

app/assets/javascripts/post_item.js
app/controllers/api/categories_controller.rb
app/views/api/categories/index.json.jbuilder
app/views/devise/registrations/new.html.haml
app/views/items/new.html.haml

#What
非同期通信の設定
#Why
カテゴリーを表示させるため

[WIP]Post item 09261045

---

app/controllers/users/confirmations_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/controllers/users/passwords_controller.rb
app/controllers/users/registrations_controller.rb
app/controllers/users/sessions_controller.rb
app/controllers/users/unlocks_controller.rb
app/models/user.rb
app/views/devise/sessions/new.html.haml
app/views/layouts/_single_header.html.haml
app/views/layouts/devise.html.haml
db/seeds.rb
spec/models/user_spec.rb

carrierwaveはファイルのバリデーションを行っていたので関係する記述を消した

fix rspec and login view

---

config/routes.rb
spec/controllers/session_controller_spec.rb
spec/rails_helper.rb

ログインのテストの途中。うまくいかないので、rails s で上手くいくのか確かめたい

Login test 2

---

app/assets/javascripts/post_item.js
app/assets/stylesheets/_items.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/post_item.scss
app/views/items/new.html.haml

#What
jqueryとjsonを使って非同期通信を行う
#Why
続き

[WIP]jquery

---

app/assets/stylesheets/users.scss
app/views/users/show.html.haml

＃WHAT
user-pageを編集しました。
＃WHY
編集が必要だから

user-page編集しました。

---

app/assets/stylesheets/login.scss
app/controllers/users_controller.rb
app/views/users/logout.html.haml

logout のビューの完成

---

app/assets/javascripts/post_item.js
app/assets/stylesheets/_items.scss
app/views/items/new.html.haml

[WIP]カテゴリー

---

README.md
app/models/address.rb
db/migrate/20190926161203_remove_address_from_user_details.rb
db/migrate/20190926165639_create_addresses.rb
db/schema.rb
spec/factories/addresses.rb
spec/models/address_spec.rb

addressモデルの作成

---

app/assets/stylesheets/_items.scss
app/assets/stylesheets/post_item.scss
app/views/devise/registrations/new.html.haml
app/views/items/new.html.haml
app/views/shared/_footers.html.haml

[WIP]Post item 09270920

---

app/assets/stylesheets/_user_registration_status_bar.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/confirmation.scss
app/assets/stylesheets/login.scss
app/assets/stylesheets/logout.scss
app/controllers/users_controller.rb
app/views/devise/registrations/new.html.haml
app/views/users/sms_confirmation.html.haml
config/routes.rb

電話番号認証用のビュー

---

app/assets/stylesheets/_items.scss
app/assets/stylesheets/confirmation.scss
app/views/items/new.html.haml

[WIP]post_item

---

app/assets/stylesheets/_items.scss
app/assets/stylesheets/sign_up2.scss
app/views/devise/registrations/new2.html.haml
app/views/items/new.html.haml

#What
投稿ページのビュー追加
#Why
本物により近づけるため

[WIP]Sign up 2 09281415

---

app/assets/javascripts/post_item.js
app/assets/stylesheets/_items.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/confirmation.scss
app/controllers/items_controller.rb
app/models/region.rb
app/views/items/new.html.haml

#What
投稿機能のページ、ビュー
#Why
本物により近づけるため

[WIP]Sign up09291155

---

app/assets/javascripts/user_detail.coffee
app/assets/stylesheets/confirmation.scss
app/assets/stylesheets/login.scss
app/assets/stylesheets/user_detail.scss
app/controllers/user_detail_controller.rb
app/helpers/user_detail_helper.rb
app/views/layouts/_single_header.html.haml
app/views/layouts/_user_registration_status_bar.html.haml
app/views/user_detail/edit.html.haml
config/routes.rb
spec/controllers/user_detail_controller_spec.rb
spec/helpers/user_detail_helper_spec.rb
spec/views/user_detail/edit.html.haml_spec.rb

本人確認ページ作成１

---

app/assets/javascripts/post_item.js
app/assets/stylesheets/_items.scss
app/views/items/new.html.haml

Sign up09301000

---

app/controllers/users_controller.rb
config/routes.rb

[WIP]新規登録（クレジットカード）

---

app/views/users/credit_card_registration.html.haml

[WIP]クレジットカード登録画面

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/user_detail.scss
app/controllers/user_detail_controller.rb
app/views/user_detail/edit.html.haml

住所などを変更できる本人情報ページを作成した。
住所等の変更に対応するため

本人確認ページの作成

---

app/assets/stylesheets/logout.scss
app/views/users/logout.html.haml

ログアウトページのアークアップを行った。
ログアウトできないと不便だから

[WIP]ログアウトページのマークアップ

---

db/seeds.rb

#What
導入
#Why
たくさんのDBを作るのは手間がかかるから

[WIP]faker

---

app/models/user.rb
app/models/user_detail.rb
spec/factories/user_details.rb
spec/models/user_detail_spec.rb
spec/models/user_spec.rb

ユーザーの新規登録とサインインができるようにした。またバリデーションをかけてそのバリデーションが効くかどうかのテストを行った。
User
#create
can save
is valid with a nickname, email, password, password_confirmation, image
is valid with a nickname, email, password, password_confirmation
is valid with a nickname that has less than 20 characters
cannot save
is invalid without nickname
is invalid without email
is invalid without password
is invalid without password_confirmation
is invalid with a duplicate email address
is invalid with a nickname that has more than 21 characters
is invalid with a password that has less than 6 characters
is invalid with a password only alphabet
is invalid with a password only number
UserDetail
#create
can save
is valid with a name_kana, name_kanji, birth_date and user
cannot save
is invalid without name_kana
is invalid …

[WIP]新規登録・ログインのバリデーションとテスト

---

app/assets/stylesheets/address.scss
app/controllers/users_controller.rb
app/views/users/address.html.haml

＃WHAT
ユーザー新規登録とログインページのコーディングを完了させました
＃WHY
マークアップを完成させるのが必要だから

ユーザー新規登録/ログインページのコーディングを完了

---

app/controllers/items_controller.rb
app/controllers/toppages_controller.rb
app/views/toppages/index.html.haml
db/seeds.rb

#What
商品一覧ページを表示させる
#Why
本物により近づけるため

[WIP]商品一覧ページ

---

app/controllers/toppages_controller.rb
app/views/toppages/index.html.haml
db/seeds.rb

[WIP]Serverside index items10022040

---

app/controllers/toppages_controller.rb
app/views/toppages/index.html.haml

#What
トップページ商品一覧表示
#Why
本物により近づけるため

Severside index items10031220

---

app/controllers/items_controller.rb
db/seeds.rb

最新の状態にするための

---

app/assets/javascripts/item.js
app/assets/javascripts/post_item.js
app/assets/stylesheets/productdetails.scss
app/views/items/show.html.haml

#What
商品詳細ページの画像スライド
#Why
本物により近づけるため

[WIP]Serverside item details10031130

---

app/assets/stylesheets/productdetails.scss
app/models/user.rb
app/views/items/show.html.haml
db/seeds.rb

#What
ユーザーのその他の出品表示
#Why
本物により近づけるため

[WIP]商品詳細画面

---

app/assets/javascripts/item.js
app/assets/stylesheets/productdetails.scss
app/controllers/items_controller.rb
app/views/items/show.html.haml

#What
【サーバサイド】商品詳細表示
#Why
本物のメルカリと同様の詳細ページ に仕上げるため

[WIP]Server side item details10061710

---

app/assets/stylesheets/_items.scss
app/views/items/new.html.haml

#What
商品出品ページ　価格表示
#Why
本物により近づけるため

[WIP]Check post item10061815

---

app/assets/javascripts/item.js
app/assets/javascripts/post_item.js

[WIP]商品出品ページ

---

app/assets/javascripts/post_item.js
app/assets/stylesheets/productdetails.scss
app/views/items/show.html.haml
app/views/users/credit_card_registration.html.haml

#What
商品出品ページ、クレジット登録画面ビュー直し
#Why
見栄えが良い方が美しいから

[WIP]Check post item10071100

---

app/assets/javascripts/post_item.js
app/assets/stylesheets/_items.scss
app/models/item.rb
app/views/items/new.html.haml

#What
商品投稿ページ　サイズ表示
#Why
本物により近づけるため

[WIP]Check post item10071800

---

app/assets/javascripts/toppage.js
app/assets/stylesheets/_toppages.scss
app/views/toppages/index.html.haml

トップページの現在のキャンペーンなどを広告するスライダーを作成した。jqueryを用いて拡張性の高い物にした。

トップページのスライドショー

---

app/assets/javascripts/modal.js
app/assets/javascripts/toppage.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/modal.scss
app/assets/stylesheets/productdetails.scss
app/controllers/items_controller.rb
app/models/item.rb
app/views/items/show.html.haml

商品削除を行える様にした。dependetn: :destroyを設定することで画像も一緒に削除される様にした
間違えて出品した際に削除を出来る様にするため

商品削除のサーバーサイド

---

app/assets/javascripts/item.js
app/assets/javascripts/post_item.js
app/assets/javascripts/syuppin.js
app/assets/stylesheets/_items.scss
app/assets/stylesheets/confirmation.scss
app/views/items/new.html.haml

#What
商品出品ページ最終チェック
#Why
本物により近づけるため

Check post item10091100

---

app/controllers/users/omniauth_callbacks_controller.rb
app/models/user.rb
app/views/users/new.html.haml
config/initializers/devise.rb

#What
FB/Google認証
#Why
メールアドレスだけではなく、SNS認証を導入することによって
ユーザーを増やすため。

[WIP]SNS認証

---

app/assets/stylesheets/card-new.scss
app/views/card/new.html.haml

＃WHAT
クレジットカードほマークアップの編集
＃WHY
必要だから

クレジットカード編集

---

app/assets/javascripts/modal.js
app/assets/javascripts/syuppin.js
app/assets/stylesheets/modal.scss

モーダルにアニメーションの追加
ターボリンクスの影響が出ない様にする

ターボリンクスによるエラーの回避
